### ISSUE TITLE
sensitive information should be protected

### ISSUE THREAD

**Issue by erdos** [jafingerhut/clj-prescreen#2]
file clj-prescreen/data/all-clojure-jira-users.clj contains houndreds of names and email addresses. it is already indexed by mayor search engines and there is a high risk of grabbing attention of spambots.

**Comment by jafingerhut** [comment]
Do you still see this file checked in?  At Alex Miller's suggestion, I recently followed Github instructions to remove this file not just from the most recent master version, but from the entire Github repo history.  Perhaps I need to try following those steps again.

Second, this information is actually public.  Anyone with Internet access can create a Clojure JIRA account in a minute, and have access to the account names, full names, and email addresses of all users.  Just go to this page and click on the name of any user you see who has updated a ticket (while logged in to your Clojure JIRA account): http://dev.clojure.org/jira/browse/CLJ

**Comment by erdos** [comment]
dear jafingerhut, thank you for your quick answer. please do what is required to protect the sensitive information. 

i see a significant difference between data visible after registration and data available to everyone. in the former the responsibility is jira's, and in the latter it is yours.

**Comment by jafingerhut** [comment]
I should have again committed the change that removes the file from the latest version, as well as the repo history.  I have deleted two different local repos I have, and cloned fresh copies.  Committing other files from one of them may have been the reason why the file accidentally got reintroduced into the Github repo.

Out of curiosity, are you planning on requesting that the remaining public source of this information be eliminated?

**Comment by erdos** [comment]
thank you for your quick action.
