### ISSUE TITLE
Repository contains personal data

### ISSUE THREAD

**Issue by chessman** [jafingerhut/clj-prescreen#5]
This repository contains my personal email along with my name. I don't want to have it in public. Now it is searchable via github search.

**Comment by jafingerhut** [comment]
You are welcome to send me a private email at andy.fingerhut@gmail.com and let me know which file and what to look for, because I'm not sure which part of the repository contains your personal email and name, since neither are obvious to me from this issue.

**Comment by jafingerhut** [comment]
If you can find any of your personal data remaining, let me know.
